### PR TITLE
Event Calendar for Elgg 3.x

### LINKED ISSUE #14: FR: Support Elgg >3
I'm wondering, why nobody else created this issue. I need support of event_calendar for Elgg >3.

Any plans to support that or are there alternatives?

### PR DESCRIPTION
**Pull request by dploeger**
Here, as promised a (probably still work in progress-)version of the Event Calendar for Elgg 3.x and up. (Developed it on 3.1) Fixes #14 

Those changes were applied:
* Rewrote page handling to use routing instead
* Replaced the different menu items to places where they better fit in the current default UI of Elgg
* Fixed database handling
* Fixed deprecations (though not all of it)
* Fixed styling issues

And I couldn't help but implement my feature from #11 as well, because we use that in our site.

I tested the following features manually:

* Layout and function of all views (paged, agenda, full)
* Create event
* Modify event
* Delete event
* Add event to private calendar and remove event

Please let me know what you think.

### CODE REVIEW

**Comment by iionly** [comment]
It's alright to include the code of PR for https://github.com/iionly/event_calendar/issues/11. The only reason it's still open is that I had no time yet to look into your PR (yes it's quite a while since you made the PR but my workload is just crazy since last year). Please don't get mad at me when I can't look into this PR anytime soon either. I will definitely consider your code when working on a release for Elgg 3!!!

**Comment by dploeger** [comment]
No problem at all. I know how that is. Thanks for checking out the code eventually. I will use my branch for now.

**Comment by mendo79** [comment]
hi, i am new here. I was not able to find the complete plugin Event_Calendar for Elgg 3.x to download.  Can you please send a link.
thnak you

**Comment by dploeger** [comment]
You can download the current state of branch issue-14 from our fork: https://github.com/wabuehamm/event_calendar/archive/issue-14.zip

**Comment by Ngseri** [comment]
dploeger,

Thank you for upgrading event_calendar plugin. I am currently use your version of event_calendar on my website. 

I found one small issue with $.colorbox in 'event_calendar/views/default/js/event_calendar/event_calendar_fullcalendar.js'. When I click on an event, the popup window displays. But at the top right corner of the popup window, it display the word 'Close' instead of 'X' symbol. To solve this issue, I used 'elgg/lightbox' instead of $.colorbox. Would you mind including this fix to your pull request for event_calender?

Thank you!

**Comment by dploeger** [comment]
@Ngseri Sure can. Would you mind creating a pull request in my repo based on the issue-14 branch there?

**Comment by Ngseri** [comment]
@dploeger I sure can. But after testing the plugin, I found two issues so far.

1) **'Export/Import'** tabs next to the 'Add event' tab do not show up. The issue is that **set_input('ical_calendar_title_menu', true)** was removed. Hence, the value of $use_titlemenu variable below is 'false'.

//in ec_ical_titlemenu( )
`$use_titlemenu = get_input('ical_calendar_title_menu', false);`

2) I have a plugin to register a format filtering (paged, agenda, by month, and full view) on the page like 'Add event/Export/Import/**Format Filtering**'. But code below **breaks** it.
//in models/model.php - event_calendar_generate_listing_params
`$event_calendar_listing_format = get_input('format', elgg_get_plugin_setting('listing_format', 'event_calendar'));`

The above code replaces two lines of code below.
```
$event_calendar_listing_format = elgg_get_plugin_setting('listing_format', 'event_calendar');
$event_calendar_listing_format = elgg_trigger_plugin_hook('event_calendar', 'get-listing-format', [], $event_calendar_listing_format);
```
Would you mind clarifying the reasons of using the new approach instead of the old one?

Thanks!

**Comment by iionly** [comment]
I've made a release for Elgg 3.X (and a second one for Elgg 3.3.X), so closing this.

**Pull request closed without merging**
